/* AbstractGame.c generated by valac 0.34.4, the Vala compiler
 * generated from AbstractGame.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_events.h>
#include <float.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_render.h>
#include <gee.h>
#include <SDL2/SDL_pixels.h>
#include <SDL2/SDL_rect.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_hints.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_audio.h>


#define BOSCO_TYPE_ABSTRACT_GAME (bosco_abstract_game_get_type ())
#define BOSCO_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame))
#define BOSCO_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))
#define BOSCO_IS_ABSTRACT_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_IS_ABSTRACT_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_ABSTRACT_GAME))
#define BOSCO_ABSTRACT_GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGameClass))

typedef struct _BoscoAbstractGame BoscoAbstractGame;
typedef struct _BoscoAbstractGameClass BoscoAbstractGameClass;
typedef struct _BoscoAbstractGamePrivate BoscoAbstractGamePrivate;

#define BOSCO_TYPE_SPRITE (bosco_sprite_get_type ())
#define BOSCO_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_SPRITE, BoscoSprite))
#define BOSCO_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_SPRITE, BoscoSpriteClass))
#define BOSCO_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_SPRITE))
#define BOSCO_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_SPRITE))
#define BOSCO_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_SPRITE, BoscoSpriteClass))

typedef struct _BoscoSprite BoscoSprite;
typedef struct _BoscoSpriteClass BoscoSpriteClass;

#define BOSCO_TYPE_FONT (bosco_font_get_type ())
#define BOSCO_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_FONT, BoscoFont))
#define BOSCO_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_FONT, BoscoFontClass))
#define BOSCO_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_FONT))
#define BOSCO_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_FONT))
#define BOSCO_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_FONT, BoscoFontClass))

typedef struct _BoscoFont BoscoFont;
typedef struct _BoscoFontClass BoscoFontClass;
#define _g_free0(var) (var = (g_free (var), NULL))
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))
#define _SDL_DestroyRenderer0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyRenderer (var), NULL)))
#define _g_ptr_array_unref0(var) ((var == NULL) ? NULL : (var = (g_ptr_array_unref (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

#define BOSCO_TYPE_COLOR (bosco_color_get_type ())
#define BOSCO_COLOR(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_COLOR, BoscoColor))
#define BOSCO_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_COLOR, BoscoColorClass))
#define BOSCO_IS_COLOR(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_COLOR))
#define BOSCO_IS_COLOR_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_COLOR))
#define BOSCO_COLOR_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_COLOR, BoscoColorClass))

typedef struct _BoscoColor BoscoColor;
typedef struct _BoscoColorClass BoscoColorClass;
#define _bosco_color_unref0(var) ((var == NULL) ? NULL : (var = (bosco_color_unref (var), NULL)))
typedef struct _BoscoSpritePrivate BoscoSpritePrivate;

#define BOSCO_TYPE_SCALE (bosco_scale_get_type ())
typedef struct _BoscoScale BoscoScale;

struct _BoscoAbstractGame {
	GObject parent_instance;
	BoscoAbstractGamePrivate * priv;
	gchar* name;
	gint width;
	gint height;
	gchar* defaultFont;
	gboolean running;
	SDL_Window* window;
	SDL_Renderer* renderer;
	GPtrArray* sprites;
	GeeArrayList* onetime;
	guint8* keys;
	gint keys_length1;
	gboolean showFps;
};

struct _BoscoAbstractGameClass {
	GObjectClass parent_class;
	void (*Events) (BoscoAbstractGame* self, SDL_Event e);
	void (*Update) (BoscoAbstractGame* self, gdouble delta);
	void (*Draw) (BoscoAbstractGame* self, gdouble delta);
	void (*Dispose) (BoscoAbstractGame* self);
	gboolean (*Initialize) (BoscoAbstractGame* self);
};

struct _BoscoAbstractGamePrivate {
	gdouble _delta;
	BoscoFont* _fpsFont;
	BoscoSprite* _fpsSprite;
	gdouble _currentTime;
	gdouble _lastTime;
	gdouble _currentFps;
	gdouble _elapsed;
	gint _frames;
	gdouble _t1;
	gdouble _t2;
	gdouble _t3;
};

struct _BoscoScale {
	gdouble x;
	gdouble y;
};

struct _BoscoSprite {
	GObject parent_instance;
	BoscoSpritePrivate * priv;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	BoscoScale scale;
	SDL_Color color;
	gboolean centered;
	gint layer;
	gint id;
};

struct _BoscoSpriteClass {
	GObjectClass parent_class;
};


static gpointer bosco_abstract_game_parent_class = NULL;

GType bosco_abstract_game_get_type (void) G_GNUC_CONST;
GType bosco_sprite_get_type (void) G_GNUC_CONST;
GType bosco_font_get_type (void) G_GNUC_CONST;
#define BOSCO_ABSTRACT_GAME_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGamePrivate))
enum  {
	BOSCO_ABSTRACT_GAME_DUMMY_PROPERTY,
	BOSCO_ABSTRACT_GAME_DELTA
};
BoscoAbstractGame* bosco_abstract_game_new (void);
BoscoAbstractGame* bosco_abstract_game_construct (GType object_type);
BoscoColor* bosco_color_new (void);
BoscoColor* bosco_color_construct (GType object_type);
gpointer bosco_color_ref (gpointer instance);
void bosco_color_unref (gpointer instance);
GParamSpec* bosco_param_spec_color (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void bosco_value_set_color (GValue* value, gpointer v_object);
void bosco_value_take_color (GValue* value, gpointer v_object);
gpointer bosco_value_get_color (const GValue* value);
GType bosco_color_get_type (void) G_GNUC_CONST;
gint bosco_abstract_game_Run (BoscoAbstractGame* self);
gboolean bosco_abstract_game_Initialize (BoscoAbstractGame* self);
void bosco_abstract_game_Events (BoscoAbstractGame* self, SDL_Event e);
void bosco_abstract_game_Update (BoscoAbstractGame* self, gdouble delta);
void bosco_abstract_game_Draw (BoscoAbstractGame* self, gdouble delta);
BoscoSprite* bosco_sprite_fromRenderedText (SDL_Renderer* renderer, BoscoFont* font, const gchar* text, SDL_Color color);
GType bosco_scale_get_type (void) G_GNUC_CONST;
BoscoScale* bosco_scale_dup (const BoscoScale* self);
void bosco_scale_free (BoscoScale* self);
void bosco_abstract_game_Dispose (BoscoAbstractGame* self);
static void bosco_abstract_game_real_Events (BoscoAbstractGame* self, SDL_Event e);
static void bosco_abstract_game_real_Update (BoscoAbstractGame* self, gdouble delta);
static void bosco_abstract_game_real_Draw (BoscoAbstractGame* self, gdouble delta);
void bosco_sprite_render (BoscoSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip);
static void bosco_abstract_game_real_Dispose (BoscoAbstractGame* self);
static gboolean bosco_abstract_game_real_Initialize (BoscoAbstractGame* self);
BoscoFont* bosco_font_fromFile (const gchar* path, gint size);
gdouble bosco_abstract_game_get_delta (BoscoAbstractGame* self);
static void bosco_abstract_game_finalize (GObject* obj);
static void _vala_bosco_abstract_game_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec);


BoscoAbstractGame* bosco_abstract_game_construct (GType object_type) {
	BoscoAbstractGame * self = NULL;
	BoscoColor* _tmp0_ = NULL;
	BoscoColor* _tmp1_ = NULL;
	self = (BoscoAbstractGame*) g_object_new (object_type, NULL);
	_tmp0_ = bosco_color_new ();
	_tmp1_ = _tmp0_;
	_bosco_color_unref0 (_tmp1_);
	return self;
}


BoscoAbstractGame* bosco_abstract_game_new (void) {
	return bosco_abstract_game_construct (BOSCO_TYPE_ABSTRACT_GAME);
}


gint bosco_abstract_game_Run (BoscoAbstractGame* self) {
	gint result = 0;
	gboolean _tmp0_ = FALSE;
	SDL_Event e = {0};
	gint64 _tmp1_ = 0LL;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = bosco_abstract_game_Initialize (self);
	if (_tmp0_ == FALSE) {
		result = -1;
		return result;
	}
	_tmp1_ = g_get_real_time ();
	self->priv->_currentTime = ((gdouble) _tmp1_) / 1000000.0;
	while (TRUE) {
		gboolean _tmp2_ = FALSE;
		gdouble _tmp20_ = 0.0;
		gint64 _tmp21_ = 0LL;
		gdouble _tmp22_ = 0.0;
		gdouble _tmp23_ = 0.0;
		gint64 _tmp24_ = 0LL;
		gdouble _tmp25_ = 0.0;
		gint64 _tmp26_ = 0LL;
		gdouble _tmp27_ = 0.0;
		gint64 _tmp28_ = 0LL;
		gboolean _tmp29_ = FALSE;
		_tmp2_ = self->running;
		if (!_tmp2_) {
			break;
		}
		while (TRUE) {
			SDL_Event _tmp3_ = {0};
			gint _tmp4_ = 0;
			SDL_Event _tmp5_ = {0};
			SDL_EventType _tmp6_ = 0;
			SDL_Event _tmp19_ = {0};
			_tmp4_ = SDL_PollEvent (&_tmp3_);
			 (e);
			e = _tmp3_;
			if (!(_tmp4_ != 0)) {
				break;
			}
			_tmp5_ = e;
			_tmp6_ = _tmp5_.type;
			switch (_tmp6_) {
				case SDL_KEYDOWN:
				{
					{
						guint8* _tmp7_ = NULL;
						gint _tmp7__length1 = 0;
						SDL_Event _tmp8_ = {0};
						SDL_KeyboardEvent _tmp9_ = {0};
						SDL_Keysym _tmp10_ = {0};
						SDL_Keycode _tmp11_ = 0;
						guint8 _tmp12_ = 0U;
						_tmp7_ = self->keys;
						_tmp7__length1 = self->keys_length1;
						_tmp8_ = e;
						_tmp9_ = _tmp8_.key;
						_tmp10_ = _tmp9_.keysym;
						_tmp11_ = _tmp10_.sym;
						_tmp7_[_tmp11_] = (guint8) 1;
						_tmp12_ = _tmp7_[_tmp11_];
					}
					break;
				}
				case SDL_KEYUP:
				{
					{
						guint8* _tmp13_ = NULL;
						gint _tmp13__length1 = 0;
						SDL_Event _tmp14_ = {0};
						SDL_KeyboardEvent _tmp15_ = {0};
						SDL_Keysym _tmp16_ = {0};
						SDL_Keycode _tmp17_ = 0;
						guint8 _tmp18_ = 0U;
						_tmp13_ = self->keys;
						_tmp13__length1 = self->keys_length1;
						_tmp14_ = e;
						_tmp15_ = _tmp14_.key;
						_tmp16_ = _tmp15_.keysym;
						_tmp17_ = _tmp16_.sym;
						_tmp13_[_tmp17_] = (guint8) 0;
						_tmp18_ = _tmp13_[_tmp17_];
					}
					break;
				}
				default:
				break;
			}
			_tmp19_ = e;
			bosco_abstract_game_Events (self, _tmp19_);
		}
		_tmp20_ = self->priv->_currentTime;
		self->priv->_lastTime = _tmp20_;
		_tmp21_ = g_get_real_time ();
		self->priv->_currentTime = ((gdouble) _tmp21_) / 1000000.0;
		_tmp22_ = self->priv->_currentTime;
		_tmp23_ = self->priv->_lastTime;
		self->priv->_delta = _tmp22_ - _tmp23_;
		_tmp24_ = g_get_real_time ();
		self->priv->_t1 = ((gdouble) _tmp24_) / 1000000.0;
		_tmp25_ = self->priv->_delta;
		bosco_abstract_game_Update (self, _tmp25_);
		_tmp26_ = g_get_real_time ();
		self->priv->_t2 = ((gdouble) _tmp26_) / 1000000.0;
		g_usleep ((gulong) 1000);
		_tmp27_ = self->priv->_delta;
		bosco_abstract_game_Draw (self, _tmp27_);
		_tmp28_ = g_get_real_time ();
		self->priv->_t3 = ((gdouble) _tmp28_) / 1000000.0;
		_tmp29_ = self->showFps;
		if (_tmp29_) {
			gint _tmp30_ = 0;
			gdouble _tmp31_ = 0.0;
			gdouble _tmp32_ = 0.0;
			gdouble _tmp33_ = 0.0;
			BoscoSprite* _tmp36_ = NULL;
			SDL_Renderer* _tmp37_ = NULL;
			BoscoFont* _tmp38_ = NULL;
			gdouble _tmp39_ = 0.0;
			gchar* _tmp40_ = NULL;
			gchar* _tmp41_ = NULL;
			SDL_Color _tmp42_ = {0};
			BoscoSprite* _tmp43_ = NULL;
			BoscoSprite* _tmp44_ = NULL;
			_tmp30_ = self->priv->_frames;
			self->priv->_frames = _tmp30_ + 1;
			_tmp31_ = self->priv->_elapsed;
			_tmp32_ = self->priv->_delta;
			self->priv->_elapsed = _tmp31_ + _tmp32_;
			_tmp33_ = self->priv->_elapsed;
			if (_tmp33_ > 1.0) {
				gint _tmp34_ = 0;
				gdouble _tmp35_ = 0.0;
				_tmp34_ = self->priv->_frames;
				_tmp35_ = self->priv->_elapsed;
				self->priv->_currentFps = ((gdouble) _tmp34_) / _tmp35_;
				self->priv->_elapsed = 0.0;
				self->priv->_frames = 0;
			}
			_tmp36_ = self->priv->_fpsSprite;
			if (_tmp36_ != NULL) {
				_g_object_unref0 (self->priv->_fpsSprite);
				self->priv->_fpsSprite = NULL;
			}
			_tmp37_ = self->renderer;
			_tmp38_ = self->priv->_fpsFont;
			_tmp39_ = self->priv->_currentFps;
			_tmp40_ = g_strdup_printf ("%2.2f", _tmp39_);
			_tmp41_ = _tmp40_;
			_tmp42_.r = (guint8) 250;
			_tmp42_.g = (guint8) 250;
			_tmp42_.b = (guint8) 250;
			_tmp43_ = bosco_sprite_fromRenderedText (_tmp37_, _tmp38_, _tmp41_, _tmp42_);
			_g_object_unref0 (self->priv->_fpsSprite);
			self->priv->_fpsSprite = _tmp43_;
			_g_free0 (_tmp41_);
			_tmp44_ = self->priv->_fpsSprite;
			_tmp44_->centered = FALSE;
		}
	}
	bosco_abstract_game_Dispose (self);
	result = 0;
	 (e);
	return result;
}


static void bosco_abstract_game_real_Events (BoscoAbstractGame* self, SDL_Event e) {
}


void bosco_abstract_game_Events (BoscoAbstractGame* self, SDL_Event e) {
	g_return_if_fail (self != NULL);
	BOSCO_ABSTRACT_GAME_GET_CLASS (self)->Events (self, e);
}


static void bosco_abstract_game_real_Update (BoscoAbstractGame* self, gdouble delta) {
}


void bosco_abstract_game_Update (BoscoAbstractGame* self, gdouble delta) {
	g_return_if_fail (self != NULL);
	BOSCO_ABSTRACT_GAME_GET_CLASS (self)->Update (self, delta);
}


static gint g_ptr_array_get_length (GPtrArray* self) {
	gint result;
	guint _tmp0_ = 0U;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->len;
	result = (gint) _tmp0_;
	return result;
}


static void g_ptr_array_set_length (GPtrArray* self, gint value) {
	gint _tmp0_ = 0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	g_ptr_array_set_size (self, _tmp0_);
}


static gpointer _g_object_ref0 (gpointer self) {
	return self ? g_object_ref (self) : NULL;
}


static void bosco_abstract_game_real_Draw (BoscoAbstractGame* self, gdouble delta) {
	SDL_Renderer* _tmp0_ = NULL;
	SDL_Renderer* _tmp1_ = NULL;
	gboolean _tmp17_ = FALSE;
	GeeArrayList* _tmp37_ = NULL;
	SDL_Renderer* _tmp38_ = NULL;
	_tmp0_ = self->renderer;
	SDL_SetRenderDrawColor (_tmp0_, (guint8) 0x0, (guint8) 0x0, (guint8) 0x0, (guint8) 0x0);
	_tmp1_ = self->renderer;
	SDL_RenderClear (_tmp1_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp2_ = FALSE;
			_tmp2_ = TRUE;
			while (TRUE) {
				GPtrArray* _tmp4_ = NULL;
				gint _tmp5_ = 0;
				gint _tmp6_ = 0;
				BoscoSprite* sprite = NULL;
				GPtrArray* _tmp7_ = NULL;
				gint _tmp8_ = 0;
				gconstpointer _tmp9_ = NULL;
				BoscoSprite* _tmp10_ = NULL;
				BoscoSprite* _tmp11_ = NULL;
				SDL_Renderer* _tmp12_ = NULL;
				BoscoSprite* _tmp13_ = NULL;
				gint _tmp14_ = 0;
				BoscoSprite* _tmp15_ = NULL;
				gint _tmp16_ = 0;
				if (!_tmp2_) {
					gint _tmp3_ = 0;
					_tmp3_ = i;
					i = _tmp3_ + 1;
				}
				_tmp2_ = FALSE;
				_tmp4_ = self->sprites;
				_tmp5_ = g_ptr_array_get_length (_tmp4_);
				_tmp6_ = _tmp5_;
				if (!(i <= (_tmp6_ - 1))) {
					break;
				}
				_tmp7_ = self->sprites;
				_tmp8_ = i;
				_tmp9_ = g_ptr_array_index (_tmp7_, (guint) _tmp8_);
				_tmp10_ = _g_object_ref0 ((BoscoSprite*) _tmp9_);
				sprite = _tmp10_;
				_tmp11_ = sprite;
				_tmp12_ = self->renderer;
				_tmp13_ = sprite;
				_tmp14_ = _tmp13_->x;
				_tmp15_ = sprite;
				_tmp16_ = _tmp15_->y;
				bosco_sprite_render (_tmp11_, _tmp12_, _tmp14_, _tmp16_, NULL);
				_g_object_unref0 (sprite);
			}
		}
	}
	_tmp17_ = self->showFps;
	if (_tmp17_) {
		BoscoSprite* _tmp18_ = NULL;
		SDL_Renderer* _tmp19_ = NULL;
		_tmp18_ = self->priv->_fpsSprite;
		_tmp19_ = self->renderer;
		bosco_sprite_render (_tmp18_, _tmp19_, 0, 0, NULL);
	}
	{
		GeeArrayList* _sprite_list = NULL;
		GeeArrayList* _tmp20_ = NULL;
		GeeArrayList* _tmp21_ = NULL;
		gint _sprite_size = 0;
		GeeArrayList* _tmp22_ = NULL;
		gint _tmp23_ = 0;
		gint _tmp24_ = 0;
		gint _sprite_index = 0;
		_tmp20_ = self->onetime;
		_tmp21_ = _g_object_ref0 (_tmp20_);
		_sprite_list = _tmp21_;
		_tmp22_ = _sprite_list;
		_tmp23_ = gee_abstract_collection_get_size ((GeeCollection*) _tmp22_);
		_tmp24_ = _tmp23_;
		_sprite_size = _tmp24_;
		_sprite_index = -1;
		while (TRUE) {
			gint _tmp25_ = 0;
			gint _tmp26_ = 0;
			gint _tmp27_ = 0;
			BoscoSprite* sprite = NULL;
			GeeArrayList* _tmp28_ = NULL;
			gint _tmp29_ = 0;
			gpointer _tmp30_ = NULL;
			BoscoSprite* _tmp31_ = NULL;
			SDL_Renderer* _tmp32_ = NULL;
			BoscoSprite* _tmp33_ = NULL;
			gint _tmp34_ = 0;
			BoscoSprite* _tmp35_ = NULL;
			gint _tmp36_ = 0;
			_tmp25_ = _sprite_index;
			_sprite_index = _tmp25_ + 1;
			_tmp26_ = _sprite_index;
			_tmp27_ = _sprite_size;
			if (!(_tmp26_ < _tmp27_)) {
				break;
			}
			_tmp28_ = _sprite_list;
			_tmp29_ = _sprite_index;
			_tmp30_ = gee_abstract_list_get ((GeeAbstractList*) _tmp28_, _tmp29_);
			sprite = (BoscoSprite*) _tmp30_;
			_tmp31_ = sprite;
			_tmp32_ = self->renderer;
			_tmp33_ = sprite;
			_tmp34_ = _tmp33_->x;
			_tmp35_ = sprite;
			_tmp36_ = _tmp35_->y;
			bosco_sprite_render (_tmp31_, _tmp32_, _tmp34_, _tmp36_, NULL);
			_g_object_unref0 (sprite);
		}
		_g_object_unref0 (_sprite_list);
	}
	_tmp37_ = gee_array_list_new (BOSCO_TYPE_SPRITE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	_g_object_unref0 (self->onetime);
	self->onetime = _tmp37_;
	_tmp38_ = self->renderer;
	SDL_RenderPresent (_tmp38_);
}


void bosco_abstract_game_Draw (BoscoAbstractGame* self, gdouble delta) {
	g_return_if_fail (self != NULL);
	BOSCO_ABSTRACT_GAME_GET_CLASS (self)->Draw (self, delta);
}


static void bosco_abstract_game_real_Dispose (BoscoAbstractGame* self) {
}


void bosco_abstract_game_Dispose (BoscoAbstractGame* self) {
	g_return_if_fail (self != NULL);
	BOSCO_ABSTRACT_GAME_GET_CLASS (self)->Dispose (self);
}


/**
         * Initialize SDL
         */
static gboolean bosco_abstract_game_real_Initialize (BoscoAbstractGame* self) {
	gboolean result = FALSE;
	gint _tmp0_ = 0;
	gint _tmp2_ = 0;
	gboolean _tmp4_ = FALSE;
	const gchar* _tmp6_ = NULL;
	gint _tmp7_ = 0;
	gint _tmp8_ = 0;
	SDL_Window* _tmp9_ = NULL;
	SDL_Window* _tmp10_ = NULL;
	SDL_Window* _tmp12_ = NULL;
	SDL_Renderer* _tmp13_ = NULL;
	SDL_Renderer* _tmp14_ = NULL;
	SDL_Renderer* _tmp16_ = NULL;
	gint _tmp17_ = 0;
	const gchar* _tmp19_ = NULL;
	gint _tmp24_ = 0;
	_tmp0_ = SDL_Init ((guint32) SDL_INIT_VIDEO);
	if (_tmp0_ < 0) {
		const gchar* _tmp1_ = NULL;
		_tmp1_ = SDL_GetError ();
		g_print ("SDL could not initialize! SDL Error: %s\n", _tmp1_);
		result = FALSE;
		return result;
	}
	_tmp2_ = IMG_Init ((gint) IMG_INIT_PNG);
	if (_tmp2_ < 0) {
		const gchar* _tmp3_ = NULL;
		_tmp3_ = SDL_GetError ();
		g_print ("SDL_image could not initialize! SDL Error: %s\n", _tmp3_);
		result = FALSE;
		return result;
	}
	_tmp4_ = SDL_SetHint (SDL_HINT_RENDER_SCALE_QUALITY, "1");
	if (!_tmp4_) {
		const gchar* _tmp5_ = NULL;
		_tmp5_ = SDL_GetError ();
		g_print ("Warning: Linear texture filtering not enabled!! SDL Error: %s\n", _tmp5_);
	}
	_tmp6_ = self->name;
	_tmp7_ = self->width;
	_tmp8_ = self->height;
	_tmp9_ = SDL_CreateWindow (_tmp6_, (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, _tmp7_, _tmp8_, (guint32) SDL_WINDOW_SHOWN);
	_SDL_DestroyWindow0 (self->window);
	self->window = _tmp9_;
	_tmp10_ = self->window;
	if (_tmp10_ == NULL) {
		const gchar* _tmp11_ = NULL;
		_tmp11_ = SDL_GetError ();
		g_print ("Window could not be created! SDL Error: %s\n", _tmp11_);
		result = FALSE;
		return result;
	}
	_tmp12_ = self->window;
	_tmp13_ = SDL_CreateRenderer (_tmp12_, -1, (guint32) (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC));
	_SDL_DestroyRenderer0 (self->renderer);
	self->renderer = _tmp13_;
	_tmp14_ = self->renderer;
	if (_tmp14_ == NULL) {
		const gchar* _tmp15_ = NULL;
		_tmp15_ = SDL_GetError ();
		g_print ("Renderer could not be created! SDL Error: %s\n", _tmp15_);
		result = FALSE;
		return result;
	}
	_tmp16_ = self->renderer;
	SDL_SetRenderDrawColor (_tmp16_, (guint8) 0xFF, (guint8) 0xFF, (guint8) 0xFF, (guint8) 0);
	_tmp17_ = TTF_Init ();
	if (_tmp17_ == (-1)) {
		const gchar* _tmp18_ = NULL;
		_tmp18_ = SDL_GetError ();
		g_print ("SDL_ttf could not initialize! SDL Error: %s\n", _tmp18_);
		result = FALSE;
		return result;
	}
	_tmp19_ = self->defaultFont;
	if (g_strcmp0 (_tmp19_, "") != 0) {
		const gchar* _tmp20_ = NULL;
		BoscoFont* _tmp21_ = NULL;
		BoscoFont* _tmp22_ = NULL;
		_tmp20_ = self->defaultFont;
		_tmp21_ = bosco_font_fromFile (_tmp20_, 16);
		_g_object_unref0 (self->priv->_fpsFont);
		self->priv->_fpsFont = _tmp21_;
		_tmp22_ = self->priv->_fpsFont;
		if (_tmp22_ == NULL) {
			const gchar* _tmp23_ = NULL;
			self->showFps = FALSE;
			_tmp23_ = SDL_GetError ();
			g_print ("Failed to load font, showFps set to false. SDL Error: %s\n", _tmp23_);
		} else {
			self->showFps = TRUE;
		}
	}
	_tmp24_ = Mix_OpenAudio (22050, AUDIO_S16LSB, 2, 4096);
	if (_tmp24_ == (-1)) {
		const gchar* _tmp25_ = NULL;
		_tmp25_ = SDL_GetError ();
		g_print ("SDL_mixer unagle to initialize! SDL Error: %s\n", _tmp25_);
	}
	result = TRUE;
	return result;
}


gboolean bosco_abstract_game_Initialize (BoscoAbstractGame* self) {
	g_return_val_if_fail (self != NULL, FALSE);
	return BOSCO_ABSTRACT_GAME_GET_CLASS (self)->Initialize (self);
}


gdouble bosco_abstract_game_get_delta (BoscoAbstractGame* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_delta;
	result = _tmp0_;
	return result;
}


static void bosco_abstract_game_class_init (BoscoAbstractGameClass * klass) {
	bosco_abstract_game_parent_class = g_type_class_peek_parent (klass);
	g_type_class_add_private (klass, sizeof (BoscoAbstractGamePrivate));
	((BoscoAbstractGameClass *) klass)->Events = bosco_abstract_game_real_Events;
	((BoscoAbstractGameClass *) klass)->Update = bosco_abstract_game_real_Update;
	((BoscoAbstractGameClass *) klass)->Draw = bosco_abstract_game_real_Draw;
	((BoscoAbstractGameClass *) klass)->Dispose = bosco_abstract_game_real_Dispose;
	((BoscoAbstractGameClass *) klass)->Initialize = bosco_abstract_game_real_Initialize;
	G_OBJECT_CLASS (klass)->get_property = _vala_bosco_abstract_game_get_property;
	G_OBJECT_CLASS (klass)->finalize = bosco_abstract_game_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), BOSCO_ABSTRACT_GAME_DELTA, g_param_spec_double ("delta", "delta", "delta", -G_MAXDOUBLE, G_MAXDOUBLE, 0.0, G_PARAM_STATIC_NAME | G_PARAM_STATIC_NICK | G_PARAM_STATIC_BLURB | G_PARAM_READABLE));
}


static void bosco_abstract_game_instance_init (BoscoAbstractGame * self) {
	GeeArrayList* _tmp0_ = NULL;
	guint8* _tmp1_ = NULL;
	self->priv = BOSCO_ABSTRACT_GAME_GET_PRIVATE (self);
	_tmp0_ = gee_array_list_new (BOSCO_TYPE_SPRITE, (GBoxedCopyFunc) g_object_ref, g_object_unref, NULL, NULL, NULL);
	self->onetime = _tmp0_;
	_tmp1_ = g_new0 (guint8, 255);
	self->keys = _tmp1_;
	self->keys_length1 = 255;
	self->showFps = FALSE;
	self->priv->_currentTime = 0.0;
	self->priv->_lastTime = 0.0;
	self->priv->_currentFps = 0.0;
	self->priv->_elapsed = 0.0;
	self->priv->_frames = 0;
	self->priv->_t1 = 0.0;
	self->priv->_t2 = 0.0;
	self->priv->_t3 = 0.0;
}


static void bosco_abstract_game_finalize (GObject* obj) {
	BoscoAbstractGame * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame);
	_g_free0 (self->name);
	_g_free0 (self->defaultFont);
	_SDL_DestroyWindow0 (self->window);
	_SDL_DestroyRenderer0 (self->renderer);
	_g_ptr_array_unref0 (self->sprites);
	_g_object_unref0 (self->onetime);
	self->keys = (g_free (self->keys), NULL);
	_g_object_unref0 (self->priv->_fpsFont);
	_g_object_unref0 (self->priv->_fpsSprite);
	G_OBJECT_CLASS (bosco_abstract_game_parent_class)->finalize (obj);
}


GType bosco_abstract_game_get_type (void) {
	static volatile gsize bosco_abstract_game_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_abstract_game_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoAbstractGameClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bosco_abstract_game_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoscoAbstractGame), 0, (GInstanceInitFunc) bosco_abstract_game_instance_init, NULL };
		GType bosco_abstract_game_type_id;
		bosco_abstract_game_type_id = g_type_register_static (G_TYPE_OBJECT, "BoscoAbstractGame", &g_define_type_info, 0);
		g_once_init_leave (&bosco_abstract_game_type_id__volatile, bosco_abstract_game_type_id);
	}
	return bosco_abstract_game_type_id__volatile;
}


static void _vala_bosco_abstract_game_get_property (GObject * object, guint property_id, GValue * value, GParamSpec * pspec) {
	BoscoAbstractGame * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BOSCO_TYPE_ABSTRACT_GAME, BoscoAbstractGame);
	switch (property_id) {
		case BOSCO_ABSTRACT_GAME_DELTA:
		g_value_set_double (value, bosco_abstract_game_get_delta (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}



