/* Config.c generated by valac 0.34.4, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define BOSCO_CONSTANTS_DATADIR "/usr/share"
#define BOSCO_CONSTANTS_PKGDATADIR "/usr/share/libbosco"
#define BOSCO_CONSTANTS_GETTEXT_PACKAGE "libbosco"
#define BOSCO_CONSTANTS_RELEASE_NAME "libbosco"
#define BOSCO_CONSTANTS_VERSION "0.0.1"



