/* Font.c generated by valac 0.34.4, the Vala compiler
 * generated from Font.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL2/SDL_ttf.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL_pixels.h>
#include <SDL2/SDL_surface.h>
#include <gio/gio.h>
#include <SDL2/SDL_rwops.h>


#define BOSCO_TYPE_FONT (bosco_font_get_type ())
#define BOSCO_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_FONT, BoscoFont))
#define BOSCO_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_FONT, BoscoFontClass))
#define BOSCO_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_FONT))
#define BOSCO_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_FONT))
#define BOSCO_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_FONT, BoscoFontClass))

typedef struct _BoscoFont BoscoFont;
typedef struct _BoscoFontClass BoscoFontClass;
typedef struct _BoscoFontPrivate BoscoFontPrivate;
#define _TTF_CloseFont0(var) ((var == NULL) ? NULL : (var = (TTF_CloseFont (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _SDL_FreeRW0(var) ((var == NULL) ? NULL : (var = (SDL_FreeRW (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))

struct _BoscoFont {
	GObject parent_instance;
	BoscoFontPrivate * priv;
	TTF_Font* innerFont;
};

struct _BoscoFontClass {
	GObjectClass parent_class;
};


static gpointer bosco_font_parent_class = NULL;

GType bosco_font_get_type (void) G_GNUC_CONST;
enum  {
	BOSCO_FONT_DUMMY_PROPERTY
};
SDL_Surface* bosco_font_render (BoscoFont* self, const gchar* text, SDL_Color color);
BoscoFont* bosco_font_fromFile (const gchar* path, gint size);
BoscoFont* bosco_font_new (void);
BoscoFont* bosco_font_construct (GType object_type);
static void bosco_font_finalize (GObject* obj);


SDL_Surface* bosco_font_render (BoscoFont* self, const gchar* text, SDL_Color color) {
	SDL_Surface* result = NULL;
	TTF_Font* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	SDL_Color _tmp2_ = {0};
	SDL_Surface* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	_tmp0_ = self->innerFont;
	_tmp1_ = text;
	_tmp2_ = color;
	_tmp3_ = TTF_RenderUTF8_Solid (_tmp0_, _tmp1_, _tmp2_);
	result = _tmp3_;
	return result;
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


BoscoFont* bosco_font_fromFile (const gchar* path, gint size) {
	BoscoFont* result = NULL;
	BoscoFont* fx = NULL;
	BoscoFont* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = bosco_font_new ();
	fx = _tmp0_;
	_tmp1_ = path;
	_tmp2_ = string_index_of (_tmp1_, "resource:///", 0);
	if (_tmp2_ == 0) {
		{
			GBytes* ptr = NULL;
			const gchar* _tmp3_ = NULL;
			gchar* _tmp4_ = NULL;
			gchar* _tmp5_ = NULL;
			GBytes* _tmp6_ = NULL;
			GBytes* _tmp7_ = NULL;
			SDL_RWops* rw = NULL;
			GBytes* _tmp8_ = NULL;
			gsize _tmp9_;
			guint8* _tmp10_ = NULL;
			GBytes* _tmp11_ = NULL;
			gsize _tmp12_ = 0UL;
			SDL_RWops* _tmp13_ = NULL;
			BoscoFont* _tmp14_ = NULL;
			SDL_RWops* _tmp15_ = NULL;
			gint _tmp16_ = 0;
			TTF_Font* _tmp17_ = NULL;
			_tmp3_ = path;
			_tmp4_ = string_substring (_tmp3_, (glong) 11, (glong) -1);
			_tmp5_ = _tmp4_;
			_tmp6_ = g_resources_lookup_data (_tmp5_, 0, &_inner_error_);
			_tmp7_ = _tmp6_;
			_g_free0 (_tmp5_);
			ptr = _tmp7_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch0_g_error;
			}
			_tmp8_ = ptr;
			_tmp10_ = g_bytes_get_data (_tmp8_, &_tmp9_);
			_tmp11_ = ptr;
			_tmp12_ = g_bytes_get_size (_tmp11_);
			_tmp13_ = SDL_RWFromMem ((void*) _tmp10_, (gint) _tmp12_);
			rw = _tmp13_;
			_tmp14_ = fx;
			_tmp15_ = rw;
			_tmp16_ = size;
			_tmp17_ = TTF_OpenFontRW (_tmp15_, 0, _tmp16_);
			_TTF_CloseFont0 (_tmp14_->innerFont);
			_tmp14_->innerFont = _tmp17_;
			_SDL_FreeRW0 (rw);
			_g_bytes_unref0 (ptr);
		}
		goto __finally0;
		__catch0_g_error:
		{
			GError* e = NULL;
			GError* _tmp18_ = NULL;
			const gchar* _tmp19_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_tmp18_ = e;
			_tmp19_ = _tmp18_->message;
			g_print ("Error loading resource: %s\n\n", _tmp19_);
			_g_error_free0 (e);
		}
		__finally0:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (fx);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	} else {
		BoscoFont* _tmp20_ = NULL;
		const gchar* _tmp21_ = NULL;
		gint _tmp22_ = 0;
		TTF_Font* _tmp23_ = NULL;
		_tmp20_ = fx;
		_tmp21_ = path;
		_tmp22_ = size;
		_tmp23_ = TTF_OpenFont (_tmp21_, _tmp22_);
		_TTF_CloseFont0 (_tmp20_->innerFont);
		_tmp20_->innerFont = _tmp23_;
	}
	result = fx;
	return result;
}


BoscoFont* bosco_font_construct (GType object_type) {
	BoscoFont * self = NULL;
	self = (BoscoFont*) g_object_new (object_type, NULL);
	return self;
}


BoscoFont* bosco_font_new (void) {
	return bosco_font_construct (BOSCO_TYPE_FONT);
}


static void bosco_font_class_init (BoscoFontClass * klass) {
	bosco_font_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = bosco_font_finalize;
}


static void bosco_font_instance_init (BoscoFont * self) {
}


static void bosco_font_finalize (GObject* obj) {
	BoscoFont * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOSCO_TYPE_FONT, BoscoFont);
	_TTF_CloseFont0 (self->innerFont);
	G_OBJECT_CLASS (bosco_font_parent_class)->finalize (obj);
}


GType bosco_font_get_type (void) {
	static volatile gsize bosco_font_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_font_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoFontClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bosco_font_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoscoFont), 0, (GInstanceInitFunc) bosco_font_instance_init, NULL };
		GType bosco_font_type_id;
		bosco_font_type_id = g_type_register_static (G_TYPE_OBJECT, "BoscoFont", &g_define_type_info, 0);
		g_once_init_leave (&bosco_font_type_id__volatile, bosco_font_type_id);
	}
	return bosco_font_type_id__volatile;
}



