/* Sprite.c generated by valac 0.34.4, the Vala compiler
 * generated from Sprite.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <string.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_pixels.h>
#include <stdlib.h>
#include <SDL2/SDL_surface.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <gio/gio.h>
#include <SDL2/SDL_rwops.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_rect.h>


#define BOSCO_TYPE_SCALE (bosco_scale_get_type ())
typedef struct _BoscoScale BoscoScale;

#define BOSCO_TYPE_SPRITE (bosco_sprite_get_type ())
#define BOSCO_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_SPRITE, BoscoSprite))
#define BOSCO_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_SPRITE, BoscoSpriteClass))
#define BOSCO_IS_SPRITE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_SPRITE))
#define BOSCO_IS_SPRITE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_SPRITE))
#define BOSCO_SPRITE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_SPRITE, BoscoSpriteClass))

typedef struct _BoscoSprite BoscoSprite;
typedef struct _BoscoSpriteClass BoscoSpriteClass;
typedef struct _BoscoSpritePrivate BoscoSpritePrivate;
#define _SDL_DestroyTexture0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyTexture (var), NULL)))

#define BOSCO_TYPE_FONT (bosco_font_get_type ())
#define BOSCO_FONT(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), BOSCO_TYPE_FONT, BoscoFont))
#define BOSCO_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), BOSCO_TYPE_FONT, BoscoFontClass))
#define BOSCO_IS_FONT(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), BOSCO_TYPE_FONT))
#define BOSCO_IS_FONT_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), BOSCO_TYPE_FONT))
#define BOSCO_FONT_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), BOSCO_TYPE_FONT, BoscoFontClass))

typedef struct _BoscoFont BoscoFont;
typedef struct _BoscoFontClass BoscoFontClass;
#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _SDL_FreeRW0(var) ((var == NULL) ? NULL : (var = (SDL_FreeRW (var), NULL)))
#define _g_bytes_unref0(var) ((var == NULL) ? NULL : (var = (g_bytes_unref (var), NULL)))
#define _g_error_free0(var) ((var == NULL) ? NULL : (var = (g_error_free (var), NULL)))

struct _BoscoScale {
	gdouble x;
	gdouble y;
};

struct _BoscoSprite {
	GObject parent_instance;
	BoscoSpritePrivate * priv;
	SDL_Texture* texture;
	gint width;
	gint height;
	gint x;
	gint y;
	BoscoScale scale;
	SDL_Color color;
	gboolean centered;
	gint layer;
	gint id;
};

struct _BoscoSpriteClass {
	GObjectClass parent_class;
};


static gpointer bosco_sprite_parent_class = NULL;
extern gint bosco_sprite_uniqueId;
gint bosco_sprite_uniqueId = 0;

GType bosco_scale_get_type (void) G_GNUC_CONST;
BoscoScale* bosco_scale_dup (const BoscoScale* self);
void bosco_scale_free (BoscoScale* self);
GType bosco_sprite_get_type (void) G_GNUC_CONST;
enum  {
	BOSCO_SPRITE_DUMMY_PROPERTY
};
GType bosco_font_get_type (void) G_GNUC_CONST;
BoscoSprite* bosco_sprite_fromRenderedText (SDL_Renderer* renderer, BoscoFont* font, const gchar* text, SDL_Color color);
BoscoSprite* bosco_sprite_new (void);
BoscoSprite* bosco_sprite_construct (GType object_type);
SDL_Surface* bosco_font_render (BoscoFont* self, const gchar* text, SDL_Color color);
void bosco_sprite_setText (BoscoSprite* self, SDL_Renderer* renderer, TTF_Font* font, const gchar* text, SDL_Color color);
BoscoSprite* bosco_sprite_fromFile (SDL_Renderer* renderer, const gchar* path);
void bosco_sprite_render (BoscoSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip);
static void bosco_sprite_finalize (GObject* obj);


BoscoScale* bosco_scale_dup (const BoscoScale* self) {
	BoscoScale* dup;
	dup = g_new0 (BoscoScale, 1);
	memcpy (dup, self, sizeof (BoscoScale));
	return dup;
}


void bosco_scale_free (BoscoScale* self) {
	g_free (self);
}


GType bosco_scale_get_type (void) {
	static volatile gsize bosco_scale_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_scale_type_id__volatile)) {
		GType bosco_scale_type_id;
		bosco_scale_type_id = g_boxed_type_register_static ("BoscoScale", (GBoxedCopyFunc) bosco_scale_dup, (GBoxedFreeFunc) bosco_scale_free);
		g_once_init_leave (&bosco_scale_type_id__volatile, bosco_scale_type_id);
	}
	return bosco_scale_type_id__volatile;
}


BoscoSprite* bosco_sprite_fromRenderedText (SDL_Renderer* renderer, BoscoFont* font, const gchar* text, SDL_Color color) {
	BoscoSprite* result = NULL;
	BoscoSprite* mt = NULL;
	BoscoSprite* _tmp0_ = NULL;
	SDL_Surface* textSurface = NULL;
	BoscoFont* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	SDL_Color _tmp3_ = {0};
	SDL_Surface* _tmp4_ = NULL;
	SDL_Surface* _tmp5_ = NULL;
	g_return_val_if_fail (renderer != NULL, NULL);
	g_return_val_if_fail (font != NULL, NULL);
	g_return_val_if_fail (text != NULL, NULL);
	_tmp0_ = bosco_sprite_new ();
	mt = _tmp0_;
	_tmp1_ = font;
	_tmp2_ = text;
	_tmp3_ = color;
	_tmp4_ = bosco_font_render (_tmp1_, _tmp2_, _tmp3_);
	textSurface = _tmp4_;
	_tmp5_ = textSurface;
	if (_tmp5_ == NULL) {
		g_print ("Unable to render text surface!\n");
		result = NULL;
		_SDL_FreeSurface0 (textSurface);
		_g_object_unref0 (mt);
		return result;
	} else {
		BoscoSprite* _tmp6_ = NULL;
		SDL_Renderer* _tmp7_ = NULL;
		SDL_Surface* _tmp8_ = NULL;
		SDL_Texture* _tmp9_ = NULL;
		BoscoSprite* _tmp10_ = NULL;
		SDL_Texture* _tmp11_ = NULL;
		_tmp6_ = mt;
		_tmp7_ = renderer;
		_tmp8_ = textSurface;
		_tmp9_ = SDL_CreateTextureFromSurface (_tmp7_, _tmp8_);
		_SDL_DestroyTexture0 (_tmp6_->texture);
		_tmp6_->texture = _tmp9_;
		_tmp10_ = mt;
		_tmp11_ = _tmp10_->texture;
		if (_tmp11_ == NULL) {
			const gchar* _tmp12_ = NULL;
			_tmp12_ = SDL_GetError ();
			g_print ("Unable to create texture from rendered text! SDL Error: %s\n", _tmp12_);
			result = NULL;
			_SDL_FreeSurface0 (textSurface);
			_g_object_unref0 (mt);
			return result;
		} else {
			BoscoSprite* _tmp13_ = NULL;
			SDL_Surface* _tmp14_ = NULL;
			gint _tmp15_ = 0;
			BoscoSprite* _tmp16_ = NULL;
			SDL_Surface* _tmp17_ = NULL;
			gint _tmp18_ = 0;
			_tmp13_ = mt;
			_tmp14_ = textSurface;
			_tmp15_ = _tmp14_->w;
			_tmp13_->width = _tmp15_;
			_tmp16_ = mt;
			_tmp17_ = textSurface;
			_tmp18_ = _tmp17_->h;
			_tmp16_->height = _tmp18_;
		}
	}
	result = mt;
	_SDL_FreeSurface0 (textSurface);
	return result;
}


void bosco_sprite_setText (BoscoSprite* self, SDL_Renderer* renderer, TTF_Font* font, const gchar* text, SDL_Color color) {
	SDL_Surface* textSurface = NULL;
	TTF_Font* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	SDL_Color _tmp2_ = {0};
	SDL_Surface* _tmp3_ = NULL;
	SDL_Surface* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	g_return_if_fail (renderer != NULL);
	g_return_if_fail (font != NULL);
	g_return_if_fail (text != NULL);
	_tmp0_ = font;
	_tmp1_ = text;
	_tmp2_ = color;
	_tmp3_ = TTF_RenderUTF8_Solid (_tmp0_, _tmp1_, _tmp2_);
	textSurface = _tmp3_;
	_tmp4_ = textSurface;
	if (_tmp4_ == NULL) {
		g_print ("Unable to render text surface\n");
	} else {
		SDL_Renderer* _tmp5_ = NULL;
		SDL_Surface* _tmp6_ = NULL;
		SDL_Texture* _tmp7_ = NULL;
		SDL_Texture* _tmp8_ = NULL;
		_tmp5_ = renderer;
		_tmp6_ = textSurface;
		_tmp7_ = SDL_CreateTextureFromSurface (_tmp5_, _tmp6_);
		_SDL_DestroyTexture0 (self->texture);
		self->texture = _tmp7_;
		_tmp8_ = self->texture;
		if (_tmp8_ == NULL) {
			const gchar* _tmp9_ = NULL;
			_tmp9_ = SDL_GetError ();
			g_print ("Unable to create texture from rendered text! SDL Error: %s\n", _tmp9_);
		} else {
			SDL_Surface* _tmp10_ = NULL;
			gint _tmp11_ = 0;
			SDL_Surface* _tmp12_ = NULL;
			gint _tmp13_ = 0;
			_tmp10_ = textSurface;
			_tmp11_ = _tmp10_->w;
			self->width = _tmp11_;
			_tmp12_ = textSurface;
			_tmp13_ = _tmp12_->h;
			self->height = _tmp13_;
		}
	}
	_SDL_FreeSurface0 (textSurface);
}


static gint string_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = strstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


static glong string_strnlen (gchar* str, glong maxlen) {
	glong result = 0L;
	gchar* end = NULL;
	gchar* _tmp0_ = NULL;
	glong _tmp1_ = 0L;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	_tmp0_ = str;
	_tmp1_ = maxlen;
	_tmp2_ = memchr (_tmp0_, 0, (gsize) _tmp1_);
	end = _tmp2_;
	_tmp3_ = end;
	if (_tmp3_ == NULL) {
		glong _tmp4_ = 0L;
		_tmp4_ = maxlen;
		result = _tmp4_;
		return result;
	} else {
		gchar* _tmp5_ = NULL;
		gchar* _tmp6_ = NULL;
		_tmp5_ = end;
		_tmp6_ = str;
		result = (glong) (_tmp5_ - _tmp6_);
		return result;
	}
}


static gchar* string_substring (const gchar* self, glong offset, glong len) {
	gchar* result = NULL;
	glong string_length = 0L;
	gboolean _tmp0_ = FALSE;
	glong _tmp1_ = 0L;
	glong _tmp8_ = 0L;
	glong _tmp14_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	glong _tmp21_ = 0L;
	gchar* _tmp22_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp1_ = offset;
	if (_tmp1_ >= ((glong) 0)) {
		glong _tmp2_ = 0L;
		_tmp2_ = len;
		_tmp0_ = _tmp2_ >= ((glong) 0);
	} else {
		_tmp0_ = FALSE;
	}
	if (_tmp0_) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		glong _tmp5_ = 0L;
		_tmp3_ = offset;
		_tmp4_ = len;
		_tmp5_ = string_strnlen ((gchar*) self, _tmp3_ + _tmp4_);
		string_length = _tmp5_;
	} else {
		gint _tmp6_ = 0;
		gint _tmp7_ = 0;
		_tmp6_ = strlen (self);
		_tmp7_ = _tmp6_;
		string_length = (glong) _tmp7_;
	}
	_tmp8_ = offset;
	if (_tmp8_ < ((glong) 0)) {
		glong _tmp9_ = 0L;
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp9_ = string_length;
		_tmp10_ = offset;
		offset = _tmp9_ + _tmp10_;
		_tmp11_ = offset;
		g_return_val_if_fail (_tmp11_ >= ((glong) 0), NULL);
	} else {
		glong _tmp12_ = 0L;
		glong _tmp13_ = 0L;
		_tmp12_ = offset;
		_tmp13_ = string_length;
		g_return_val_if_fail (_tmp12_ <= _tmp13_, NULL);
	}
	_tmp14_ = len;
	if (_tmp14_ < ((glong) 0)) {
		glong _tmp15_ = 0L;
		glong _tmp16_ = 0L;
		_tmp15_ = string_length;
		_tmp16_ = offset;
		len = _tmp15_ - _tmp16_;
	}
	_tmp17_ = offset;
	_tmp18_ = len;
	_tmp19_ = string_length;
	g_return_val_if_fail ((_tmp17_ + _tmp18_) <= _tmp19_, NULL);
	_tmp20_ = offset;
	_tmp21_ = len;
	_tmp22_ = g_strndup (((gchar*) self) + _tmp20_, (gsize) _tmp21_);
	result = _tmp22_;
	return result;
}


BoscoSprite* bosco_sprite_fromFile (SDL_Renderer* renderer, const gchar* path) {
	BoscoSprite* result = NULL;
	SDL_Surface* loadedSurface = NULL;
	BoscoSprite* mt = NULL;
	BoscoSprite* _tmp0_ = NULL;
	const gchar* _tmp1_ = NULL;
	gint _tmp2_ = 0;
	SDL_Surface* _tmp20_ = NULL;
	GError * _inner_error_ = NULL;
	g_return_val_if_fail (renderer != NULL, NULL);
	g_return_val_if_fail (path != NULL, NULL);
	_tmp0_ = bosco_sprite_new ();
	mt = _tmp0_;
	_tmp1_ = path;
	_tmp2_ = string_index_of (_tmp1_, "resource:///", 0);
	if (_tmp2_ == 0) {
		{
			GBytes* ptr = NULL;
			const gchar* _tmp3_ = NULL;
			gchar* _tmp4_ = NULL;
			gchar* _tmp5_ = NULL;
			GBytes* _tmp6_ = NULL;
			GBytes* _tmp7_ = NULL;
			SDL_RWops* rw = NULL;
			GBytes* _tmp8_ = NULL;
			gsize _tmp9_;
			guint8* _tmp10_ = NULL;
			GBytes* _tmp11_ = NULL;
			gsize _tmp12_ = 0UL;
			SDL_RWops* _tmp13_ = NULL;
			SDL_RWops* _tmp14_ = NULL;
			SDL_Surface* _tmp15_ = NULL;
			_tmp3_ = path;
			_tmp4_ = string_substring (_tmp3_, (glong) 11, (glong) -1);
			_tmp5_ = _tmp4_;
			_tmp6_ = g_resources_lookup_data (_tmp5_, 0, &_inner_error_);
			_tmp7_ = _tmp6_;
			_g_free0 (_tmp5_);
			ptr = _tmp7_;
			if (G_UNLIKELY (_inner_error_ != NULL)) {
				goto __catch2_g_error;
			}
			_tmp8_ = ptr;
			_tmp10_ = g_bytes_get_data (_tmp8_, &_tmp9_);
			_tmp11_ = ptr;
			_tmp12_ = g_bytes_get_size (_tmp11_);
			_tmp13_ = SDL_RWFromMem ((void*) _tmp10_, (gint) _tmp12_);
			rw = _tmp13_;
			_tmp14_ = rw;
			_tmp15_ = SDL_LoadBMP_RW (_tmp14_, 0);
			_SDL_FreeSurface0 (loadedSurface);
			loadedSurface = _tmp15_;
			_SDL_FreeRW0 (rw);
			_g_bytes_unref0 (ptr);
		}
		goto __finally2;
		__catch2_g_error:
		{
			GError* e = NULL;
			GError* _tmp16_ = NULL;
			const gchar* _tmp17_ = NULL;
			e = _inner_error_;
			_inner_error_ = NULL;
			_SDL_FreeSurface0 (loadedSurface);
			loadedSurface = NULL;
			_tmp16_ = e;
			_tmp17_ = _tmp16_->message;
			g_print ("Error loading resource: %s\n\n", _tmp17_);
			_g_error_free0 (e);
		}
		__finally2:
		if (G_UNLIKELY (_inner_error_ != NULL)) {
			_g_object_unref0 (mt);
			_SDL_FreeSurface0 (loadedSurface);
			g_critical ("file %s: line %d: uncaught error: %s (%s, %d)", __FILE__, __LINE__, _inner_error_->message, g_quark_to_string (_inner_error_->domain), _inner_error_->code);
			g_clear_error (&_inner_error_);
			return NULL;
		}
	} else {
		const gchar* _tmp18_ = NULL;
		SDL_Surface* _tmp19_ = NULL;
		_tmp18_ = path;
		_tmp19_ = IMG_Load (_tmp18_);
		_SDL_FreeSurface0 (loadedSurface);
		loadedSurface = _tmp19_;
	}
	_tmp20_ = loadedSurface;
	if (_tmp20_ == NULL) {
		const gchar* _tmp21_ = NULL;
		_tmp21_ = SDL_GetError ();
		g_print ("Unable to load image! SDL Error: %s\n", _tmp21_);
		result = NULL;
		_g_object_unref0 (mt);
		_SDL_FreeSurface0 (loadedSurface);
		return result;
	} else {
		BoscoSprite* _tmp22_ = NULL;
		SDL_Renderer* _tmp23_ = NULL;
		SDL_Surface* _tmp24_ = NULL;
		SDL_Texture* _tmp25_ = NULL;
		BoscoSprite* _tmp26_ = NULL;
		SDL_Texture* _tmp27_ = NULL;
		BoscoSprite* _tmp28_ = NULL;
		SDL_Texture* _tmp29_ = NULL;
		_tmp22_ = mt;
		_tmp23_ = renderer;
		_tmp24_ = loadedSurface;
		_tmp25_ = SDL_CreateTextureFromSurface (_tmp23_, _tmp24_);
		_SDL_DestroyTexture0 (_tmp22_->texture);
		_tmp22_->texture = _tmp25_;
		_tmp26_ = mt;
		_tmp27_ = _tmp26_->texture;
		SDL_SetTextureBlendMode (_tmp27_, SDL_BLENDMODE_BLEND);
		_tmp28_ = mt;
		_tmp29_ = _tmp28_->texture;
		if (_tmp29_ == NULL) {
			const gchar* _tmp30_ = NULL;
			const gchar* _tmp31_ = NULL;
			_tmp30_ = path;
			_tmp31_ = SDL_GetError ();
			g_print ("Unable to create texture from %s! SDL Error: %s\n", _tmp30_, _tmp31_);
		} else {
			BoscoSprite* _tmp32_ = NULL;
			SDL_Surface* _tmp33_ = NULL;
			gint _tmp34_ = 0;
			BoscoSprite* _tmp35_ = NULL;
			SDL_Surface* _tmp36_ = NULL;
			gint _tmp37_ = 0;
			_tmp32_ = mt;
			_tmp33_ = loadedSurface;
			_tmp34_ = _tmp33_->w;
			_tmp32_->width = _tmp34_;
			_tmp35_ = mt;
			_tmp36_ = loadedSurface;
			_tmp37_ = _tmp36_->h;
			_tmp35_->height = _tmp37_;
		}
	}
	result = mt;
	_SDL_FreeSurface0 (loadedSurface);
	return result;
}


void bosco_sprite_render (BoscoSprite* self, SDL_Renderer* renderer, gint x, gint y, SDL_Rect* clip) {
	guint _tmp0_ = 0U;
	SDL_Rect* _tmp1_ = NULL;
	gint w = 0;
	BoscoScale _tmp5_ = {0};
	gdouble _tmp6_ = 0.0;
	guint _tmp7_ = 0U;
	SDL_Rect* _tmp8_ = NULL;
	gint h = 0;
	BoscoScale _tmp12_ = {0};
	gdouble _tmp13_ = 0.0;
	gint _tmp14_ = 0;
	gboolean _tmp15_ = FALSE;
	gint _tmp19_ = 0;
	gboolean _tmp20_ = FALSE;
	SDL_Texture* _tmp24_ = NULL;
	SDL_Color _tmp25_ = {0};
	guint8 _tmp26_ = 0U;
	SDL_Color _tmp27_ = {0};
	guint8 _tmp28_ = 0U;
	SDL_Color _tmp29_ = {0};
	guint8 _tmp30_ = 0U;
	SDL_Renderer* _tmp31_ = NULL;
	SDL_Texture* _tmp32_ = NULL;
	gint _tmp33_ = 0;
	gint _tmp34_ = 0;
	gint _tmp35_ = 0;
	gint _tmp36_ = 0;
	SDL_Rect _tmp37_ = {0};
	g_return_if_fail (self != NULL);
	g_return_if_fail (renderer != NULL);
	_tmp1_ = clip;
	if (_tmp1_ == NULL) {
		gint _tmp2_ = 0;
		_tmp2_ = self->width;
		_tmp0_ = (guint) _tmp2_;
	} else {
		SDL_Rect* _tmp3_ = NULL;
		guint _tmp4_ = 0U;
		_tmp3_ = clip;
		_tmp4_ = (*_tmp3_).w;
		_tmp0_ = _tmp4_;
	}
	_tmp5_ = self->scale;
	_tmp6_ = _tmp5_.x;
	w = (gint) (_tmp0_ * _tmp6_);
	_tmp8_ = clip;
	if (_tmp8_ == NULL) {
		gint _tmp9_ = 0;
		_tmp9_ = self->height;
		_tmp7_ = (guint) _tmp9_;
	} else {
		SDL_Rect* _tmp10_ = NULL;
		guint _tmp11_ = 0U;
		_tmp10_ = clip;
		_tmp11_ = (*_tmp10_).h;
		_tmp7_ = _tmp11_;
	}
	_tmp12_ = self->scale;
	_tmp13_ = _tmp12_.y;
	h = (gint) (_tmp7_ * _tmp13_);
	_tmp15_ = self->centered;
	if (_tmp15_) {
		gint _tmp16_ = 0;
		gint _tmp17_ = 0;
		_tmp16_ = x;
		_tmp17_ = w;
		_tmp14_ = _tmp16_ - (_tmp17_ / 2);
	} else {
		gint _tmp18_ = 0;
		_tmp18_ = x;
		_tmp14_ = _tmp18_;
	}
	x = _tmp14_;
	_tmp20_ = self->centered;
	if (_tmp20_) {
		gint _tmp21_ = 0;
		gint _tmp22_ = 0;
		_tmp21_ = y;
		_tmp22_ = h;
		_tmp19_ = _tmp21_ - (_tmp22_ / 2);
	} else {
		gint _tmp23_ = 0;
		_tmp23_ = y;
		_tmp19_ = _tmp23_;
	}
	y = _tmp19_;
	_tmp24_ = self->texture;
	_tmp25_ = self->color;
	_tmp26_ = _tmp25_.r;
	_tmp27_ = self->color;
	_tmp28_ = _tmp27_.g;
	_tmp29_ = self->color;
	_tmp30_ = _tmp29_.b;
	SDL_SetTextureColorMod (_tmp24_, _tmp26_, _tmp28_, _tmp30_);
	_tmp31_ = renderer;
	_tmp32_ = self->texture;
	_tmp33_ = x;
	_tmp34_ = y;
	_tmp35_ = w;
	_tmp36_ = h;
	_tmp37_.x = _tmp33_;
	_tmp37_.y = _tmp34_;
	_tmp37_.w = (guint) _tmp35_;
	_tmp37_.h = (guint) _tmp36_;
	SDL_RenderCopy (_tmp31_, _tmp32_, NULL, &_tmp37_);
}


BoscoSprite* bosco_sprite_construct (GType object_type) {
	BoscoSprite * self = NULL;
	self = (BoscoSprite*) g_object_new (object_type, NULL);
	return self;
}


BoscoSprite* bosco_sprite_new (void) {
	return bosco_sprite_construct (BOSCO_TYPE_SPRITE);
}


static void bosco_sprite_class_init (BoscoSpriteClass * klass) {
	bosco_sprite_parent_class = g_type_class_peek_parent (klass);
	G_OBJECT_CLASS (klass)->finalize = bosco_sprite_finalize;
}


static void bosco_sprite_instance_init (BoscoSprite * self) {
	BoscoScale _tmp0_ = {0};
	SDL_Color _tmp1_ = {0};
	gint _tmp2_ = 0;
	gint _tmp3_ = 0;
	memset (&_tmp0_, 0, sizeof (BoscoScale));
	_tmp0_.x = 1.0;
	_tmp0_.y = 1.0;
	self->scale = _tmp0_;
	memset (&_tmp1_, 0, sizeof (SDL_Color));
	_tmp1_.r = (guint8) 255;
	_tmp1_.g = (guint8) 255;
	_tmp1_.b = (guint8) 255;
	_tmp1_.a = (guint8) 255;
	self->color = _tmp1_;
	self->centered = TRUE;
	self->layer = 0;
	_tmp2_ = bosco_sprite_uniqueId;
	bosco_sprite_uniqueId = _tmp2_ + 1;
	_tmp3_ = bosco_sprite_uniqueId;
	self->id = _tmp3_;
}


static void bosco_sprite_finalize (GObject* obj) {
	BoscoSprite * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BOSCO_TYPE_SPRITE, BoscoSprite);
	_SDL_DestroyTexture0 (self->texture);
	G_OBJECT_CLASS (bosco_sprite_parent_class)->finalize (obj);
}


GType bosco_sprite_get_type (void) {
	static volatile gsize bosco_sprite_type_id__volatile = 0;
	if (g_once_init_enter (&bosco_sprite_type_id__volatile)) {
		static const GTypeInfo g_define_type_info = { sizeof (BoscoSpriteClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bosco_sprite_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BoscoSprite), 0, (GInstanceInitFunc) bosco_sprite_instance_init, NULL };
		GType bosco_sprite_type_id;
		bosco_sprite_type_id = g_type_register_static (G_TYPE_OBJECT, "BoscoSprite", &g_define_type_info, 0);
		g_once_init_leave (&bosco_sprite_type_id__volatile, bosco_sprite_type_id);
	}
	return bosco_sprite_type_id__volatile;
}



